/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Utils.SVGImage;
import com.formdev.flatlaf.themes.FlatMacLightLaf;

/**
 *
 * @author X1
 */
public class QLNH_details extends javax.swing.JFrame {
    SVGImage svgSet = new SVGImage();
    /**
     * Creates new form QLTT_Brand
     */
    public QLNH_details() {
        initComponents();
        setLocationRelativeTo(null);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEdit = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        txtMaTT = new javax.swing.JTextField();
        txtTenTT = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtMaTT1 = new javax.swing.JTextField();
        txtTenTT1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel28 = new javax.swing.JLabel();
        txtTenTT2 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtMaTT2 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        btnCancel_B = new javax.swing.JButton();
        btnViewHide = new javax.swing.JButton();

        btnEdit.setBackground(new java.awt.Color(255, 220, 11));
        btnEdit.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("LƯU");

        jLabel24.setText("Mã Thuộc Tính:");

        txtMaTT.setEnabled(false);

        jLabel23.setText("Tên Thuộc Tính:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã SP", "Danh Mục", "Brand", "Kích Cỡ", "Màu Sắc", "Chất Liệu", "Giá Nhập", "Số Lượng", "Thuế", "Tổng Tiền"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 870, 239));

        jPanel2.setBackground(new java.awt.Color(220, 117, 28));

        jLabel2.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("THÔNG TIN NHẬP HÀNG");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(jLabel2)
                .addContainerGap(342, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, -1));

        jLabel25.setText("Mã Phiếu:");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 86, 88, -1));

        txtMaTT1.setEnabled(false);
        getContentPane().add(txtMaTT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 110, 140, -1));

        txtTenTT1.setEnabled(false);
        txtTenTT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenTT1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtTenTT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 210, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 880, 10));

        jLabel28.setText("Tên Nhân Viên:");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 88, 20));

        txtTenTT2.setEnabled(false);
        getContentPane().add(txtTenTT2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 210, -1));

        jLabel27.setText("Nhà Cung Cấp:");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 88, 20));

        txtMaTT2.setEnabled(false);
        getContentPane().add(txtMaTT2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 140, -1));

        jLabel29.setText("Ngày Lập:");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 80, 88, 20));

        btnCancel_B.setBackground(new java.awt.Color(204, 0, 51));
        btnCancel_B.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnCancel_B.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel_B.setText("HỦY");
        getContentPane().add(btnCancel_B, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 450, 90, 30));

        btnViewHide.setText("EXPORT");
        btnViewHide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewHideActionPerformed(evt);
            }
        });
        getContentPane().add(btnViewHide, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 450, 90, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTenTT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenTT1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenTT1ActionPerformed

    private void btnViewHideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewHideActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewHideActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        FlatMacLightLaf.setup();
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLNH_details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel_B;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnViewHide;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtMaTT;
    private javax.swing.JTextField txtMaTT1;
    private javax.swing.JTextField txtMaTT2;
    private javax.swing.JTextField txtTenTT;
    private javax.swing.JTextField txtTenTT1;
    private javax.swing.JTextField txtTenTT2;
    // End of variables declaration//GEN-END:variables
}
